name: Test Version Management

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test'
        required: true
        default: '1.0.2'

jobs:
  test-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Show current version
      run: |
        echo "Current version in pom.xml:"
        grep -oP '<version>\K[^<]+' pom.xml | head -1
    - name: Update version
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "Updating version to: $VERSION"
        sed -i "s/<version>.*<\/version>/<version>$VERSION<\/version>/" pom.xml
        echo "Updated pom.xml version:"
        grep -oP '<version>\K[^<]+' pom.xml | head -1
    - name: Show final version
      run: |
        echo "Final version in pom.xml:"
        grep -oP '<version>\K[^<]+' pom.xml | head -1 